doskey ll=dir
doskey ls=dir
doskey clear=cls
doskey pwd=cd
doskey cp=copy $*
doskey mv=move $*
doskey rm=del $*
doskey mkdir=mkdir $*
doskey rmdir=rmdir $*
doskey touch=type nul > $*
doskey cat=type $*
doskey grep=findstr $*
doskey echo=echo $*
doskey whoami=whoami
doskey ifconfig=ipconfig
doskey ping=ping $*
doskey top=tasklist
doskey ps=tasklist
doskey kill=taskkill /PID $* /F
doskey man=echo No man pages in cmd. Use Google :)
doskey history=doskey /history